/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senac.alg2.notepadapp.ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Angelo
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form notepad
     */
    public Notepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        caixaTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        arquivo = new javax.swing.JMenu();
        novo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        salvar = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        cortar = new javax.swing.JMenuItem();
        copiar = new javax.swing.JMenuItem();
        colar = new javax.swing.JMenuItem();
        selecionarTudo = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Notepad--");
        setIconImage(icone);
        setMinimumSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane2.setBorder(null);

        caixaTexto.setColumns(20);
        caixaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        caixaTexto.setRows(5);
        jScrollPane2.setViewportView(caixaTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        arquivo.setText("Arquivo");

        novo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        novo.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\file-earmark-plus.png")); // NOI18N
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        arquivo.add(novo);

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrir.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\folder2-open.png")); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        arquivo.add(abrir);

        salvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salvar.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\save2.png")); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        arquivo.add(salvar);

        sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        sair.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\box-arrow-right.png")); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        arquivo.add(sair);

        jMenuBar1.add(arquivo);

        editar.setText("Editar");

        cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cortar.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\scissors.png")); // NOI18N
        cortar.setText("Cortar");
        cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortarActionPerformed(evt);
            }
        });
        editar.add(cortar);

        copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copiar.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\clipboard-plus.png")); // NOI18N
        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        editar.add(copiar);

        colar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        colar.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\clipboard-check.png")); // NOI18N
        colar.setText("Colar");
        colar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colarActionPerformed(evt);
            }
        });
        editar.add(colar);

        selecionarTudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        selecionarTudo.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\clipboard2-fill.png")); // NOI18N
        selecionarTudo.setText("Selecionar Tudo");
        selecionarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarTudoActionPerformed(evt);
            }
        });
        editar.add(selecionarTudo);

        jMenuBar1.add(editar);

        ajuda.setText("Ajuda");

        sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        sobre.setIcon(new javax.swing.ImageIcon("G:\\Angelo\\Documents\\Documentos SDD\\1_SENAC\\Alg II\\Notepad JAVA\\imgSrc\\question-circle.png")); // NOI18N
        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        ajuda.add(sobre);

        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(873, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        Object[] options = {"Confirmar", "Cancelar"};

        int escolha = JOptionPane.showOptionDialog(null, "Ao escolher essa opção, todo o texto será apagado.\n\nDeseja continuar?", "Novo Arquivo", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

        if (escolha == 0) {
            caixaTexto.setText(" ");
        }

    }//GEN-LAST:event_novoActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        JOptionPane.showMessageDialog(null, "   Notepad--™\n\n    Desenvolvido por Ângelo Baracho Ferreira: https://github.com/Anbfer \n\n    O Notepad--™ é um editor de texto simples desenvolvido em Java.\n    Ele oferece uma interface gráfica intuitiva, onde os usuários podem criar, editar e salvar documentos de texto.", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_sobreActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos de Texto (*.txt)", "txt");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showSaveDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();
            String path = arquivo.getAbsolutePath();

            if (!path.toLowerCase().endsWith(".txt")) {
                arquivo = new File(path + ".txt");
            }

            try {
                String conteudo = caixaTexto.getText();
                FileWriter escreve = new FileWriter(arquivo);
                escreve.write(conteudo);
                escreve.close();
                JOptionPane.showMessageDialog(null, "Arquivo Salvo", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos de Texto (*.txt)", "txt");
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();
            try {
                BufferedReader leitor = new BufferedReader(new FileReader(arquivo));
                String linha;
                StringBuilder conteudo = new StringBuilder();
                while ((linha = leitor.readLine()) != null) {
                    conteudo.append(linha).append("\n");
                }
                leitor.close();
                caixaTexto.setText(conteudo.toString());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_abrirActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        Object[] options = {"Confirmar", "Cancelar"};

        int escolha = JOptionPane.showOptionDialog(null, "Deseja encerrar o programa? Todos as modificações não salvas serão perdidas", "Fechar", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (escolha == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairActionPerformed

    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortarActionPerformed
        caixaTexto.cut();
    }//GEN-LAST:event_cortarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        caixaTexto.copy();
    }//GEN-LAST:event_copiarActionPerformed

    private void colarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colarActionPerformed
        caixaTexto.paste();
    }//GEN-LAST:event_colarActionPerformed

    private void selecionarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarTudoActionPerformed
        caixaTexto.selectAll();
    }//GEN-LAST:event_selecionarTudoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] options = {"Fechar", "Cancelar"};

        int escolha = JOptionPane.showOptionDialog(rootPane, "Deseja encerrar o programa? Todos as modificações não salvas serão perdidas", "Fechar", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (escolha == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    Image icone = Toolkit.getDefaultToolkit().getImage(".\\src\\main\\java\\senac\\alg2\\notepadapp\\ui\\img\\journals.png");

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenu arquivo;
    private javax.swing.JTextArea caixaTexto;
    private javax.swing.JMenuItem colar;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem cortar;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem novo;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem salvar;
    private javax.swing.JMenuItem selecionarTudo;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
